version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start etl-demo
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/etl-demo
      ENV: dev
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
